### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by ooguz** [Decury/decury#4]
Hello everyone,

The license of the project is GNU GPL v2 now. This license has so many issues. 

First of all, the GNU GPL v2 license is obsolete now, it's upgraded by version 3, and so it's not recommended even by FSF itself. Also GNU GPL v2 is not compatible with GNU GPL v3 which is the license most of the copylefted software are using now. 

Congratulations for using a [copyleft](https://copyleft.org) license, but I guess you are not involved so much with licenses. 

GNU GPL licenses are copyleft licenses. With copylefted licenses, the derivatives of the work must licensed under the same license or another copyleft license.

GNU GPL set the term "copyleft" at the very beginning of free software. On free software philosophy, the important topic is user's freedom. Richard M. Stallman thought that a free software should stay free, consequently users as well.

But when we are talking about a web application, GNU GPL's copyleft can be insufficient. In GPL, you have to redistribute the source code with copies of software; but there comes a problem about web applications, because they are running on a server, not in our computers. GNU AGPL v3 was authored to solve this problem; if you run an AGPL'd software in a server (in other words if software is used over networks) you have to distribute the source code of it.

But why we need this? I'll give an example on Decury. With this license; if somebody fork Decuty and create a public Git repository, they must license their fork with the same license GPL v3 according to the conditions of it. But, if they add some extra code/features to Decury and create a website called Recury.cc or something like that, they don't have to distribute the source code. Because, they are running the software, not you.

To resolve this problems, I strongly recommend to switch GNU AGPL v3 immediately. This license will protect our software from vultures of proprietarians. 

With love,

**Comment by tansiret** [comment]
@mkg20001 @leungyauming @bufgix what are your thoughts on this PR?

**Comment by leungyauming** [comment]
I agree @ooguz 's idea of switching to GNU AGPL v3 as it seems like GNU GPL v2 is really not suitable for Decury's purpose and usage.

**Comment by mkg20001** [comment]
Same. I guess we should do it then?

**Comment by TarikAkin** [comment]
I strongly disagree with this change, this prevents me to smuggle your code into my fucking software (pecury https://pecury.github.io)

**Comment by TarikAkin** [comment]
Why the fuck my comment is being deleted? Isn't this a free platform?

**Comment by TarikAkin** [comment]
Looks like you pals dont know anything about free software. WTF is deleting comments?

**Comment by TarikAkin** [comment]
> I strongly disagree with this change, this prevents me to smuggle your code into my fucking software (pecury https://pecury.github.io)

**Comment by leungyauming** [comment]
> > I strongly disagree with this change, this prevents me to smuggle your code into my fucking software (pecury https://pecury.github.io)

Free platform doesn't mean that you can post useless suggestions. I am sorry but you will be ban from this org if you continue what you are doing, and you will not be able to post any issues, comments and pull requests.

**Comment by ooguz** [comment]
I'll prepare a PR for license upgrade, I'll inform in approximately half an hour.

**Comment by ooguz** [comment]
If you approve #6 then the license will be changed.

**Comment by tansiret** [comment]
Done! Thanks for your noble advice.
