### ISSUE TITLE
Let's merge pecury and decury

### ISSUE THREAD

**Issue by TarikAkin** [Decury/decury#5]
Let's merge pecury and decury https://github.com/pecury/pecury

**Comment by TarikAkin** [comment]
Pecury has the same goal with decury, being the most shittiest software that ever existed

**Comment by TarikAkin** [comment]
Let's become the most shitty software, together!

**Comment by TarikAkin** [comment]
pecury.github.io

**Comment by TarikAkin** [comment]
Conditions for merging two applications:
1 - promise me you'll keep my fucking software the shittest one

**Comment by TarikAkin** [comment]
2 - maybe you can write your names, but this is a maybe. I'm still not sure about it because this fucking software belongs to me

**Comment by mkg20001** [comment]
U serious bro? xD

**Comment by TarikAkin** [comment]
ofc

**Comment by mkg20001** [comment]
nope. under the given ridiculous conditions this is a clear nope from me.

**Comment by leungyauming** [comment]
Issue's suggestion denied.

**Comment by TarikAkin** [comment]
why the fuck this is denied

**Comment by TarikAkin** [comment]
How much do you want to merge these 2 fucking shitty softwares

**Comment by TarikAkin** [comment]
I can give you bribe, 10$ each?

**Comment by mkg20001** [comment]
you want ban? (https://help.github.com/en/github/building-a-strong-community/blocking-a-user-from-your-organization)

**Comment by TarikAkin** [comment]
No, I want right of free speech but looks like you are not going to give me that even you claim to be a 'FREE SOFTWARE'. Please dont use terminology without knowing what it means

**Comment by TarikAkin** [comment]
HEEY
